version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sentiment_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sentiment_network

  flask_api:
    build:
      context: ./api
    image: pipe-flask_api:latest
    container_name: sentiment_api
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sentiment_db
    networks:
      - sentiment_network

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark_master
    user: root
    # Comando corregido para mantener el proceso vivo
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - .:/opt/spark/work-dir:rw # El punto '.' mapea la raíz de tu proyecto
      - ./data:/opt/spark/data:rw
    networks:
      - sentiment_network

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark_worker
    user: root
    # Conexión directa al master dentro de la red interna
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - sentiment_network

networks:
  sentiment_network:
    driver: bridge

volumes:
  mongo_data:
