services:
  mongodb:
    image: mongo:latest
    container_name: sentiment_mongo
    ports:
      - "2717:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sentiment_network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment_jenkins
    user: root
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sentiment_network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  flask_api:
    build:
      context: ./api
    container_name: sentiment_api
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sentiment_db
    networks:
      - sentiment_network

  spark-master:
    image: bitnami/spark:3.5 # Cambio a imagen oficial ligera
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark/scripts
      - ./data:/opt/spark/data
    networks:
      - sentiment_network

  spark-worker:
    image: bitnami/spark:3.5 # Cambio a imagen oficial ligera
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark/data
    networks:
      - sentiment_network

networks:
  sentiment_network:
    driver: bridge

volumes:
  mongo_data:
  jenkins_home:
